<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GeneralsettingsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('generalsettings')->delete();

        \DB::table('generalsettings')->insert(array(
            0 =>
            array(
                'id' => 1,
                'logo' => null,
                'favicon' => null,
                'header_email' => 'smtp',
                'header_phone' => '0123 456789',
                'colors' => '#186155',
                'loader' => null,
                'admin_loader' => null,
                'is_talkto' => 0,
                'talkto' => '',
                'is_jivochat' => 0,
                'jivochat' => '',
                'team_show_whatsapp' => 1,
                'team_show_header' => 1,
                'is_brands' => 1,
                'team_show_footer' => 1,
                'is_language' => 1,
                'is_loader' => 1,
                'map_key' => 'AIzaSyB1GpE4qeoJ__70UZxvX9CTMUTZRZNHcu8',
                'is_disqus' => 0,
                'disqus' => '',
                'is_contact' => 1,
                'is_faq' => 0,
                'guest_checkout' => 1,
                'stripe_check' => 0,
                'cod_check' => 1,
                'stripe_key' => 'pk_test_UnU1Coi1p5qFGwtpjZMRMgJM',
                'stripe_secret' => 'sk_test_QQcg3vGsKRPlW6T3dXcNJsor',
                'currency_format' => 0,
                'withdraw_fee' => 5.0,
                'withdraw_charge' => 5.0,
                'tax' => 0.0,
                'shipping_cost' => 5.0,
                'smtp_host' => null,
                'smtp_port' => null,
                'smtp_user' => null,
                'smtp_pass' => null,
                'from_email' => null,
                'from_name' => null,
                'is_smtp' => 1,
                'is_comment' => 1,
                'is_currency' => 1,
                'add_cart' => 'Successfully Added To Cart',
                'out_stock' => 'Out Of Stock',
                'add_wish' => 'Add To Wishlist',
                'already_wish' => 'Already Added To Wishlist',
                'wish_remove' => 'Successfully Removed From The Wishlist',
                'add_compare' => 'Successfully Added To Compare',
                'already_compare' => 'Already Added To Compare',
                'compare_remove' => 'Successfully Removed From The Compare',
                'color_change' => 'Successfully Changed The Color',
                'coupon_found' => 'Coupon Found',
                'no_coupon' => 'No Coupon Found',
                'already_coupon' => 'Coupon Already Applied',
                'order_title' => 'THANK YOU FOR YOUR PURCHASE.',
                'order_text' => 'We\'ll email you an order confirmation with details and tracking info.',
                'is_affilate' => 0,
                'affilate_charge' => 0,
                'affilate_banner' => null,
                'already_cart' => 'Already Added To Cart',
                'fixed_commission' => 0.0,
                'percentage_commission' => 0.0,
                'multiple_shipping' => 1,
                'multiple_packaging' => 1,
                'vendor_ship_info' => 0,
                'reg_vendor' => 1,
                'paypal_text' => 'Pay via your PayPal account.',
                'stripe_text' => 'Pay via your Credit Card.',
                'header_color' => '#ffffff',
                'footer_color' => '#1c2129',
                'footer_text_color' => '#ffffff',
                'copyright_color' => '#1d2024',
                'is_admin_loader' => 1,
                'menu_color' => '#ff5500',
                'menu_hover_color' => '#02020c',
                'is_home' => 1,
                'is_verification_email' => 0,
                'instamojo_key' => 'test_172371aa837ae5cad6047dc3052',
                'instamojo_token' => 'test_4ac5a785e25fc596b67dbc5c267',
                'instamojo_text' => 'Pay via your Instamojo account.',
                'is_instamojo' => 0,
                'instamojo_sandbox' => 0,
                'is_paystack' => 0,
                'paystack_key' => 'pk_test_162a56d42131cbb01932ed0d2c48f9cb99d8e8e2',
                'paystack_email' => 'junnuns@gmail.com',
                'paystack_text' => 'Pay via your Paystack account.',
                'wholesell' => 0,
                'is_capcha' => 1,
                'error_banner' => null,
                'is_popup' => 0,
                'is_newsletter_popup' => 0,
                'popup_background' => '',
                'invoice_logo' => null,
                'user_image' => null,
                'vendor_color' => '#666666',
                'is_secure' => 0,
                'is_report' => 1,
                'paypal_check' => 0,
                'paypal_business' => 'shaon143-facilitator-1@gmail.com',
                'footer_logo' => null,
                'email_encryption' => null,
                'paytm_merchant' => 'tkogux49985047638244',
                'paytm_secret' => 'LhNGUUKE9xCQ9xY8',
                'paytm_website' => 'WEBSTAGING',
                'paytm_industry' => 'Retail',
                'is_paytm' => 0,
                'paytm_text' => 'Pay via your Paytm account.',
                'paytm_mode' => 'live',
                'is_molly' => 0,
                'molly_key' => 'test_5HcWVs9qc5pzy36H9Tu9mwAyats33J',
                'molly_text' => 'Pay with Molly Payment.',
                'is_razorpay' => 0,
                'razorpay_key' => 'rzp_test_xDH74d48cwl8DF',
                'razorpay_secret' => 'cr0H1BiQ20hVzhpHfHuNbGri',
                'razorpay_text' => 'Pay via your Razorpay account.',
                'show_stock' => 0,
                'is_maintain' => 1,
                'domain' => 'crowstore.agenciacrow.com.br',
                'is_default' => 1,
                'product_percent' => 0,
                'lang_id' => 1,
                'currency_id' => 1,
                'show_currency_values' => 0,
                'show_product_prices' => 1,
                'reference_code' => 0,
                'ref_color' => '#186155',
                'is_cart' => 1,
                'is_simplified_checkout' => 0,
                'simplified_checkout_number' => null,
                'is_standard_checkout' => 1,
                'is_bancard' => 1,
                'bancard_public_key' => '',
                'bancard_private_key' => '',
                'bancard_mode' => 'live',
                'is_mercadopago' => 0,
                'mercadopago_access_token' => '',
                'is_whatsapp' => 0,
                'whatsapp_number' => null,
                'is_correios' => 1,
                'correios_cep' => null,
                'localcep_start' => null,
                'localcep_end' => null,
                'correios_width' => null,
                'correios_height' => null,
                'correios_length' => null,
                'correios_weight' => null,
                'is_cielo' => 1,
                'cielo_merchantid' => '',
                'is_pagseguro' => 1,
                'pagseguro_token' => '',
                'pagseguro_email' => '',
                'is_pagseguro_sandbox' => 1,
                'country_ship' => null,
                'is_pagopar' => 0,
                'pagopar_public_key' => null,
                'pagopar_private_key' => null,
                'bank_check' => 0,
                'ftp_folder' => null,
                'is_pagarme' => 0,
                'pagarme_encryption_key' => null,
                'pagarme_api_key' => null,
                'is_comprasparaguai' => 0,
                'store_comprasparaguai' => 1,
                'is_lojaupdate' => 0,
                'store_lojaupdate' => 1,
                'switch_highlight_currency' => 0,
                'is_rede' => 0,
                'is_rede_sandbox' => 0,
                'rede_token' => null,
                'rede_pv' => null,
                'rede_installments' => 0,
            ),
        ));
    }
}
